[[redirects]]
  from = "/*"
  to = "http://live2-ott.izzigo.tv/:splat"
  status = 200
  force = true
  headers = {User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36", Referer = "https://www.izzigo.tv/"}
